server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://admin:1234@localhost:10138/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
